[GTK4.'org.gnome.desktop.interface']
color-scheme = 'prefer-dark'

[PROTEUSLAPTOP]
DPIScale = 1.916667
keyboardBacklightDevice = 'platform::kbd_backlight'
mpv.vulkan-device = 'AMD Radeon 780M (RADV GFX1103_R1)'
rofi.dpi = 96
rofi.width = "750px"
waybar.marginTop = 6
waybar.marginLeftRight = 4
waybar.windowFontSize = '16px'
waybar.tooltipFontSize = '16px'
waybar.moduleMarginLeftRight = '2px'
waybar.modulePadding = '0 5px'
waybar.windowRewrite = '''
"class<ario>": "&#xf0386;", // music-circle
"class<Alacritty>": "&#xf018d;", // console
"class<Alacritty> title<.*helix.*>": "&#xf0684;", // dna
"class<Anki>": "&#xf0638;", // cards
"class<Bitwarden>": "&#xf0bc4;", // shield-key
"class<blender>": "&#xf00ab;", // blender-software
"class<com.obsproject.Studio>": "&#xf0210;", // fan
"class<doublecmd>": "&#xf024b;", // folder
"class<firefox>": "&#xf0239;", // firefox
"class<firefox> title<.*(bilibili|YouTube).*>": "&#xf07f4;", // television-classic
"class<hyprland-share-picker>": "&#xf0496;", // share
"class<mpv>": "&#xf040c;", // play-circle
"class<org.fcitx.fcitx5-config-qt>": "&#xf09f9;", // keyboard-settings
"class<org.inkscape.Inkscape>": "&#xf02f5;", // image-filter-hdr
"class<org.pwmt.zathura>": "&#xf0f6d;", // music-accidental-sharp
"class<org.telegram.desktop>": "&#xf048a;", // send
"class<steam>": "&#xf04d3;", // steam
"class<waybar>": "&#xf00e4;" // bug'''
waybar.privacyConfig = '''
"icon-spacing": 4,
"icon-size": 18,
"transition-duration": 250,
"modules": [
  {
    "type": "screenshare",
    "tooltip": true,
    "tooltip-icon-size": 22
  },
  {
    "type": "audio-out",
    "tooltip": true,
    "tooltip-icon-size": 22
  },
  {
    "type": "audio-in",
    "tooltip": true,
    "tooltip-icon-size": 22
  }
]'''

[[PROTEUSLAPTOP.hyprland.monitors]]
# 3440x1440 on the left-upper
name = 'eDP-1'
modeline = 'preferred, 0x0, 1.916667, bitdepth, 10'
workspace = [ 4, 5, 6 ]
deckSwitch = 'Lid Switch'
wallpaper = '/home/proteus/Pictures/wallpaper-3.jpg'
wallpaperMode = 'contain'

[[PROTEUSLAPTOP.hyprland.monitors]]
name = 'DP-2'
modeline = 'preferred, auto-left, 1.333333, bitdepth, 10'
workspace = [ 1, 2, 3 ]
wallpaper = '/home/proteus/Pictures/wallpaper-3.jpg'
wallpaperMode = 'contain'

[[PROTEUSLAPTOP.hyprland.monitors]]
name = 'DP-3'
modeline = 'preferred, auto-right, 2, transform, 1, bitdepth, 10'
workspace = [ 7, 8, 9, 10 ]

[[PROTEUSLAPTOP.pipewire.sources]]
# Name of pulse device (pactl)
name = 'alsa-mic-alc287'
# Description of pulse device (pactl)
desc = 'Mic ALC287 Analog'
# Alsa path
path = 'hw:Generic_1,0'

[[PROTEUSLAPTOP.pipewire.sources]]
name = 'alsa-mic-dmic'
desc = 'MIC DMIC HIFI Capture'
path = 'hw:acp63,0'

[[PROTEUSLAPTOP.pipewire.sinks]]
name = 'alsa-dmix-alc287'
desc = 'PCM ALC287 Analog'
path = 'dmix:Generic_1,0'

[[PROTEUSLAPTOP.pipewire.sinks]]
name = 'alsa-dmix-hdmi0'
desc = 'PCM HDMI Port 0'
path = 'dmix:Generic,3'

[[PROTEUSLAPTOP.pipewire.sinks]]
name = 'alsa-dmix-hdmi1'
desc = 'PCM HDMI Port 1'
path = 'dmix:Generic,7'

[[PROTEUSLAPTOP.pipewire.sinks]]
name = 'alsa-dmix-hdmi2'
desc = 'PCM HDMI Port 2'
path = 'dmix:Generic,8'
