theme = 'gruvbox'

[editor]
bufferline = "multiple"
color-modes = true
line-number = 'relative'
rulers = [80, 120]
soft-wrap.enable = true
true-color = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = ["diagnostics", "version-control", "selections", "position", "file-encoding", "file-line-ending", "file-type"]

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "none"

[keys.insert]
"C-c" = "normal_mode"

[keys.normal]
"F5" = [":config-reload", ":lsp-restart"]
