[[language]]
name = "cpp"
auto-format = true

[[language]]
name = "markdown"
language-servers = [{ name = "ltex" }]

[language-server.ltex]
command = "ltex-ls"

[language-server.texlab.config.texlab]
chktex.onOpenAndSave = true
chktex.onEdit = true
forwardSearch.executable = 'zathura'
forwardSearch.args = ['--synctex-forward', '%l:1:%f', '%p']

[language-server.texlab.config.texlab.build]
executable = 'latexmk'
args = ['-cd', '-pdflua', '-halt-on-error', '-interaction=nonstopmode', '-synctex=1', '%f']
onSave = true
forwardSearchAfter = true

