[COMMON]
waybar.windowRewrite = '''
"class<ario>": "&#xf0386;", // music-circle
"class<Alacritty>": "&#xf018d;", // console
"class<Alacritty> title<.*helix.*>": "&#xf0684;", // dna
"class<Anki>": "&#xf0638;", // cards
"class<Bitwarden>": "&#xf0bc4;", // shield-key
"class<blender>": "&#xf00ab;", // blender-software
"class<com.obsproject.Studio>": "&#xf0210;", // fan
"class<doublecmd>": "&#xf024b;", // folder
"class<firefox>": "&#xf0239;", // firefox
"class<firefox> title<.*(bilibili|YouTube).*>": "&#xf07f4;", // television-classic
"class<hyprland-share-picker>": "&#xf0496;", // share
"class<mpv>": "&#xf040c;", // play-circle
"class<org.fcitx.fcitx5-config-qt>": "&#xf09f9;", // keyboard-settings
"class<org.inkscape.Inkscape>": "&#xf02f5;", // image-filter-hdr
"class<org.pwmt.zathura>": "&#xf0f6d;", // music-accidental-sharp
"class<org.telegram.desktop>": "&#xf048a;", // send
"class<steam>": "&#xf04d3;", // steam
"class<imv|(ueberzugpp_[a-z0-9]{10})>": "&#xf02e9;", // image
"class<waybar>": "&#xf00e4;" // bug'''
waybar.privacyConfig = '''
"icon-spacing": 4,
"icon-size": 18,
"transition-duration": 250,
"modules": [
  {
    "type": "screenshare",
    "tooltip": true,
    "tooltip-icon-size": 22
  },
  {
    "type": "audio-out",
    "tooltip": true,
    "tooltip-icon-size": 22
  },
  {
    "type": "audio-in",
    "tooltip": true,
    "tooltip-icon-size": 22
  }
]'''
